//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitiy_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Urunler()
        {
            this.Tbl_Satıs = new HashSet<Tbl_Satıs>();
        }
    
        public int Urun_Id { get; set; }
        public string Urun_Ad { get; set; }
        public string Urun_Marka { get; set; }
        public Nullable<decimal> Urun_Fiyat { get; set; }
        public Nullable<short> Urun_Stok { get; set; }
        public Nullable<bool> Urun_Durum { get; set; }
        public Nullable<int> Urun_Kategori { get; set; }
    
        public virtual Tbl_Kategoriler Tbl_Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satıs> Tbl_Satıs { get; set; }
    }
}
