//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitiy_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Satıs
    {
        public int Satıs_Id { get; set; }
        public Nullable<decimal> Satıs_Fiyat { get; set; }
        public Nullable<int> Satıs_Urun { get; set; }
        public Nullable<int> Satıs_Musteri { get; set; }
        public Nullable<System.DateTime> Satıs_Tarih { get; set; }
    
        public virtual Tbl_Musteriler Tbl_Musteriler { get; set; }
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
    }
}
